# Generated by Django 6.0.7 on 2026-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_options_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
