# Generated by Django 6.0.7 on 2026-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_maximum_stock_product_minimum_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maximum_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
