# Generated by Django 6.0.7 on 2026-09-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_notification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.product'),
        ),
    ]
