# Generated by Django 6.0.7 on 2026-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_notification_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
