# Generated by Django 6.0.7 on 2026-09-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_image_url_stockmovement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('STOCK_MOVEMENT', 'Stock Movement')], max_length=20),
        ),
    ]
